<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IptvPlayer.Contracts\IptvPlayer.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" />
  </ItemGroup>
</Project>
